src/main/java/jp/co/team_assignment/entity/Search.java
package jp.co.team_assignment.entity;

import java.sql.Timestamp;

public class Search {
	private int id;
	private String hashtag;
	private String hashtag_name;
	private String text;
	private String profile_text;
	private String publish;
	private String user_name;
	private String name;
	private String firstDate;
	private String finalDate;
	private String searchUsers;
	private String searchTexts;
	private String searchHashtags;
	private Timestamp created_date;


	public Timestamp getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Timestamp created_date) {
		this.created_date = created_date;
	}
	public String getProfile_text() {
		return profile_text;
	}
	public void setProfile_text(String profile_text) {
		this.profile_text = profile_text;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getHashtag_name() {
		return hashtag_name;
	}
	public void setHashtag_name(String hashtag_name) {
		this.hashtag_name = hashtag_name;
	}
	public String getPublish() {
		return publish;
	}
	public void setPublish(String publish) {
		this.publish = publish;
	}
	public String getSearchTexts() {
		return searchTexts;
	}
	public void setSearchTexts(String searchTexts) {
		this.searchTexts = searchTexts;
	}
	public String getSearchHashtags() {
		return searchHashtags;
	}
	public void setSearchHashtags(String searchHashtags) {
		this.searchHashtags = searchHashtags;
	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getHashtag() {
		return hashtag;
	}
	public void setHashtag(String hashtag) {
		this.hashtag = hashtag;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	public String getFirstDate() {
		return firstDate;
	}
	public void setFirstDate(String firstDate) {
		this.firstDate = firstDate;
	}
	public String getFinalDate() {
		return finalDate;
	}
	public void setFinalDate(String finalDate) {
		this.finalDate = finalDate;
	}
	public String getSearchUsers() {
		return searchUsers;
	}
	public void setSearchUsers(String searchUsers) {
		this.searchUsers = searchUsers;
	}

}

src/main/java/jp/co/team_assignment/form/SearchForm.java
package jp.co.team_assignment.form;

import java.util.Date;

public class SearchForm {
	private int id;
	private String hashtag;
	private String hashtag_name;
	private String text;
	private String profile_text;
	private String publish;
	private String user_name;
	private String name;
	private String joined_date;
	private String firstDate;
	private String finalDate;
	private String firstDateTime;
	private String finalDateTime;
	private int career_id;
	private String position_name;
	private String searchUsers;
	private String searchTexts;
	private String searchHashtags;
	private Date created_date;


	public int getCareer_id() {
		return career_id;
	}
	public void setCareer_id(int career_id) {
		this.career_id = career_id;
	}
	public String getPosition_name() {
		return position_name;
	}
	public void setPosition_name(String position_name) {
		this.position_name = position_name;
	}
	public String getJoined_date() {
		return joined_date;
	}
	public void setJoined_date(String joined_date) {
		this.joined_date = joined_date;
	}
	public String getJoined_date_disp() {
		String month = this.joined_date.substring(4);
		String ret = this.joined_date.substring(0, 4) + "年" + month;
		return ret;
	}
	public void setJoined_date_disp(String joined_date) {
		this.joined_date = joined_date;
	}
	public Date getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Date created_date) {
		this.created_date = created_date;
	}
	public String getProfile_text() {
		return profile_text;
	}
	public void setProfile_text(String profile_text) {
		this.profile_text = profile_text;
	}
	public int getId() {
		return id;
	}
	public void setId(int id) {
		this.id = id;
	}
	public String getHashtag_name() {
		return hashtag_name;
	}
	public void setHashtag_name(String hashtag_name) {
		this.hashtag_name = hashtag_name;
	}
	public String getPublish() {
		return publish;
	}
	public void setPublish(String publish) {
		this.publish = publish;
	}
	public String getSearchTexts() {
		return searchTexts;
	}
	public void setSearchTexts(String searchTexts) {
		this.searchTexts = searchTexts;
	}
	public String getSearchHashtags() {
		return searchHashtags;
	}
	public void setSearchHashtags(String searchHashtags) {
		this.searchHashtags = searchHashtags;
	}

	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getHashtag() {
		return hashtag;
	}
	public void setHashtag(String hashtag) {
		this.hashtag = hashtag;
	}
	public String getText() {
		return text;
	}
	public void setText(String text) {
		this.text = text;
	}
	public String getUser_name() {
		return user_name;
	}
	public void setUser_name(String user_name) {
		this.user_name = user_name;
	}
	public String getFirstDate() {
		return firstDate;
	}
	public void setFirstDate(String firstDate) {
		this.firstDate = firstDate;
	}
	public String getFinalDate() {
		return finalDate;
	}
	public void setFinalDate(String finalDate) {
		this.finalDate = finalDate;
	}
	public String getFirstDateTime() {
		return firstDate + " 00:00:00";
	}
	public void setFirstDateTime(String firstDateTime) {
		this.firstDateTime = firstDateTime;
	}
	public String getFinalDateTime() {
		return finalDate + " 23:59:59";
	}
	public void setFinalDateTime(String finalDateTime) {
		this.finalDateTime = finalDateTime;
	}
	public String getSearchUsers() {
		return searchUsers;
	}
	public void setSearchUsers(String searchUsers) {
		this.searchUsers = searchUsers;
	}
}

src/main/java/jp/co/team_assignment/form/SignUpForm.java
package jp.co.team_assignment.form;

import java.sql.Timestamp;

import javax.validation.constraints.AssertFalse;
import javax.validation.constraints.AssertTrue;
import javax.validation.constraints.Min;
import javax.validation.constraints.Pattern;
import javax.validation.constraints.Size;

import org.apache.commons.lang.StringUtils;
import org.hibernate.validator.constraints.NotBlank;



public class SignUpForm {
	private Integer id;

	@Pattern(regexp ="^(([0-9a-zA-Z!#\\$%&'\\*\\+\\-/=\\?\\^_`\\{\\}\\|~]+(\\.[0-9a-zA-Z!#\\$%&'\\*\\+\\-/=\\?\\^_`\\{\\}\\|~]+)*)|(\"[^\"]*\"))@[0-9a-zA-Z!#\\$%&'\\*\\+\\-/=\\?\\^_`\\{\\}\\|~]+(\\.[0-9a-zA-Z!#\\$%&'\\*\\+\\-/=\\?\\^_`\\{\\}\\|~]+)*$",
			message ="メールアドレスが不正やで")
	@Size(max=40)
	@NotBlank(message = "メールアドレスを入力してな")
	private String mail_address;
	private int[] personality_id;

	@NotBlank(message = "名前を入力してな")
    private String name;

	@Min(value = 1, message = "部署を選択してな")
	private int position_id;

	private int hashtag_id;
	private String color_code;
	private String icon;
	private int career_id;
	@Pattern(regexp = "[0-9]{6}", message = "入社年月は数字6桁で入力してな")
	@NotBlank(message = "入社年月を入力してな")
	private String joined_date;


	private String profile_text;


	@AssertTrue(message="プロフィールは100文字以内で入力してな")
	public boolean isValidProfile() {
		if(this.profile_text != null && this.profile_text.length() <= 100) {
			return true;
		}
	return false;
	}
	private Timestamp created_date;
	private Timestamp updated_date;

	@AssertFalse(message="同じパスワードを入力してな")
	public boolean isValidPasswordCheck(){
		if(!StringUtils.isBlank(this.password)
				&& !StringUtils.isBlank(this.confirmPassword)
				&& !this.password.equals(this.confirmPassword)) {
			return true;
			}
		return false;
	}


	@NotBlank(message = "パスワードを入力してな")
	@Size(max=30)
	private String password;

	@NotBlank(message = "確認用パスワードを入力してな")
	@Size(max=30)
	private String confirmPassword;


	public String getConfirmPassword() {
		return confirmPassword;
	}
	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getMail_address() {
		return mail_address;
	}
	public void setMail_address(String mail_address) {
		this.mail_address = mail_address;
	}
	public int[] getPersonality_id() {
		return personality_id;
	}
	public void setPersonality_id(int[] personality_id) {
		this.personality_id = personality_id;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public int getPosition_id() {
		return position_id;
	}
	public void setPosition_id(int position_id) {
		this.position_id = position_id;
	}
	public int getHashtag_id() {
		return hashtag_id;
	}
	public void setHashtag_id(int hashtag_id) {
		this.hashtag_id = hashtag_id;
	}
	public String getColor_code() {
		return color_code;
	}
	public void setColor_code(String color_code) {
		this.color_code = color_code;
	}
	public String getIcon() {
		return icon;
	}
	public void setIcon(String icon) {
		this.icon = icon;
	}
	public int getCareer_id() {
		return career_id;
	}
	public void setCareer_id(int career_id) {
		this.career_id = career_id;
	}
	public String getJoined_date() {
		return joined_date;
	}
	public void setJoined_date(String joined_date) {
		this.joined_date = joined_date;
	}
	public String getProfile_text() {
		return profile_text;
	}
	public void setProfile_text(String profile_text) {
		this.profile_text = profile_text;
	}
	public Timestamp getCreated_date() {
		return created_date;
	}
	public void setCreated_date(Timestamp created_date) {
		this.created_date = created_date;
	}
	public Timestamp getUpdated_date() {
		return updated_date;
	}
	public void setUpdated_date(Timestamp updated_date) {
		this.updated_date = updated_date;
	}
}

src/main/java/jp/co/team_assignment/controller/SearchController.java
package jp.co.team_assignment.controller;

import java.util.List;

import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import jp.co.team_assignment.dto.SearchDto;
import jp.co.team_assignment.form.SearchForm;
import jp.co.team_assignment.service.SearchService;

@Controller
public class SearchController {

	@Autowired
	HttpSession session;

	@Autowired
	private SearchService searchService;

	@RequestMapping(value = "/search/", method = RequestMethod.GET)
	public String search(Model model) {
/*		int loginId = ((User)session.getAttribute("loginUser"));*/
		SearchForm form = new SearchForm();
		model.addAttribute("SearchForm", form);
		model.addAttribute("message", "検索してもええで");
		return "search";
	}

	@RequestMapping(value = "/search/", params = "searchTags", method = RequestMethod.GET)
	public String searchHashtag(@ModelAttribute("SearchForm") SearchForm form, Model model) {
/*		System.out.println(form.getHashtag());*/
		List<SearchDto> hashtagList = searchService.searchHashtags(form);
		model.addAttribute("SearchForm", form);
		model.addAttribute("searchHashtags", hashtagList);
/*		System.out.println(hashtagList.size());*/
	    model.addAttribute("message", "検索結果やで");
		return "search";
	}

	@RequestMapping(value = "/search/", params = "searchTexts", method = RequestMethod.GET)
	public String searchText(@ModelAttribute("SearchForm") SearchForm form, Model model) {
		List<SearchDto> textList = searchService.searchTexts(form);
/*//		System.out.println(textList.size());
//		System.out.println(form);
*/		model.addAttribute("SearchForm", form);
		model.addAttribute("searchTexts", textList);
	    model.addAttribute("message", "検索結果やで");
		return "search";
	}


	@RequestMapping(value = "/search/", params = "searchUsers", method = RequestMethod.GET)
	public String searchUser(@ModelAttribute("SearchForm") SearchForm form, Model model) {
		/*SearchForm form = new SearchForm();*/
/*		System.out.println(form.getUser_name());*/
		List<SearchDto> userList = searchService.searchUsers(form);
/*		System.out.println(userList.size());*/
		model.addAttribute("SearchForm", form);
		model.addAttribute("searchUsers", userList);
	    model.addAttribute("message", "検索結果やで");

		return "search";
	}

}

src/main/webapp/WEB-INF/view/login.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>"/>
<title>ログイン</title>
<script type="text/javascript" src='<c:url value="/resources/js/jquery-3.3.1.min.js"/>'></script>
<script type="text/javascript" src='<c:url value="/resources/js/javascript.js"/>'></script>

</head>
<body>
<div class="main-container">
	<div class="logo-area">
		<div class="logo">
			<img src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-0/s180x540/18485929_102296287022938_2353850535678539105_n.png?_nc_cat=0&oh=eab1aaef25b6ccc9debf7b6697912dc8&oe=5BE2B29C" width="120%" height="100%" >
		</div>
	</div>
	<div class="main-area">
		<p id=login-message>社内の人脈、広げへん？</p>
		<%-- <h1 id="sign-in" >${message}</h1> --%>
		<form:form modelAttribute="userForm" >
			<div><form:errors path="*"  /></div><br>
		<%--  action="../profile/" --%>
				<form:input path="mail_address" placeholder="Email Address" class="required"/><br/><br/>
				<form:input type="password" path="password" showPassword="false" placeholder="Password" class="required"/>
		        <input type="submit" id="sign-in" value="Sign In"  />

	    </form:form>
	</div>
</div>

</body>
</html>

src/main/webapp/WEB-INF/view/otherProfile.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>


<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>"/>
<title>プロフィール</title>
<script type="text/javascript" src="main.js"></script>
</head>
<body>
	<header>
		<a href="../../profile/">
			<img src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-0/s180x540/18485929_102296287022938_2353850535678539105_n.png?_nc_cat=0&oh=eab1aaef25b6ccc9debf7b6697912dc8&oe=5BE2B29C"  id="header-logo" >
		</a>
		<div class="right-menu">
		<a href="../../profile/"><i class="fas fa-home" >プロフィール</i></a>
		<a href="../../search/"><i class="fas fa-search">検索</i></a>
		<a href="../../update/${loginUser.id}/"><i class="fas fa-edit">編集</i></a>
		<c:if test="${loginUser.admin_flg != 0}">
		<a href="../../signUp/"><i class="fas fa-user-plus">新規登録</i></a></c:if>
		<a href="../../login/"><i class="fas fa-sign-out-alt">ログアウト</i></a>		</div>
		<div class="header-bottom1"></div>
		<div class="header-bottom2"></div>
		<div class="header-bottom3"></div>
		<div class="header-bottom4"></div>
		<div class="header-bottom5"></div>
	</header>


<span id="left-area">
<h2>${otherUsers.name}さんの<br>
　　プロフィール <img src="./profile/?id=${search.id}"></h2>
   	<span id="profile-box2">
	<form:form modelAttribute="SearchForm" method="get" class="otherPlofile-search">
		<div><form:errors path="*"  /></div><br>
		<form:input path="id" value="${search.id}" name="others" type="hidden"/>
<div class="user-name">
		    ${otherUsers.name} <img src="./profile/?id=${loginUser.id}">
		</div>
   		 プロフィール: <br>${otherUsers.profile_text}<br><br>
   		 部署: ${otherUsers.position_name}<br>
   		 ${otherUsers.joined_date_disp}月
   		 <c:if test="${otherUsers.career_id == 0}">
		    新卒入社
		 </c:if>
		 <c:if test="${otherUsers.career_id == 1}">
		    中途入社
		</c:if>
		<%-- ${otherUsers.personalities_name} --%>
	</form:form>
	</span>
</span>

<div class="right-area">
	<h2>投稿一覧</h2>

		<c:forEach items="${textLists}" var="textList">
			<c:if test="${otherUsers.text != null}">
				<p>本文: <c:out value="${textList.text}"></c:out></p>
					<p><c:if test="${ not empty textList.hashtag_name }">
		 		<p>#<c:out value="${textList.hashtag_name}"></c:out></p></c:if>
				<p>by<c:out value="${otherUsers.name}"></c:out></p>
				<p>日時:<c:out value="${textList.created_date}"></c:out></p><br>
			</c:if>
		</c:forEach>
			 	<h4>${message}</h4>

</div>
<!--
<a href="/team_assignment/profile/">自分のプロフィールに戻る</a> -->
</body>
</html>

src/main/webapp/WEB-INF/view/profile.jsp
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<c:url value="/resources/css/style.css"/>"/>
<title>プロフィール</title>
<script type="text/javascript" src='<c:url value="/resources/js/jquery-3.3.1.min.js"/>'></script>
<script type="text/javascript" src='<c:url value="/resources/js/javascript.js"/>'></script>
</head>
<body>
	<header>
		<a href="../profile/">
			<img src="https://scontent-nrt1-1.xx.fbcdn.net/v/t1.0-0/s180x540/18485929_102296287022938_2353850535678539105_n.png?_nc_cat=0&oh=eab1aaef25b6ccc9debf7b6697912dc8&oe=5BE2B29C"  id="header-logo" >
		</a>
		<div class="right-menu">
		<a href="../search/"><i class="fas fa-search">検索</i></a>
		<a href="../update/${loginUser.id}/"><i class="fas fa-edit">編集</i></a>
		<c:if test="${loginUser.admin_flg != 0}">
		<a href="../signUp/"><i class="fas fa-user-plus">新規登録</i></a></c:if>
		<a href="../login/"><i class="fas fa-sign-out-alt">ログアウト</i></a>		</div>
		<div class="header-bottom1"></div>
		<div class="header-bottom2"></div>
		<div class="header-bottom3"></div>
		<div class="header-bottom4"></div>
		<div class="header-bottom5"></div>
	</header>




<!-- 	<main class="Main" role="main">
	  <div id="borderBlack" class="border">
	      <div class="border-inner"></div>
	      <div class="border-inner"></div>
	      <div class="border-inner"></div>
	      <div class="border-inner"></div>
	  </div>
	      <div id="wrapper"></div>
	</main> -->





<%-- 	<p id="plofile-title">${profileMessage}</p> --%>
    <span id="left-area">
    	<span id="profile-box">

    	<div class="user-name">
		    ${loginUser.name} <img src="./profile/?id=${loginUser.id}">
		</div><c:if test="${loginUser.profile_text != null}"><br>
		   プロフィール:<br>${loginUser.profile_text}<br></c:if><br>

		    部署: ${loginUser.position_name}<br>
		    ${loginUser.joined_date_disp}月
		    <%-- ${fn:substring( "${loginUser.joined_date}" , 1 , 4 ) } 年 --%>

		    <c:if test="${loginUser.career_id == 0}">
		    新卒入社
		    </c:if>
		    <c:if test="${loginUser.career_id == 1}">
		    中途入社
		    </c:if>
	    </span>
	</span>


<%-- 		<span class="popupModal1">
			<input type="radio" name="modalPop" id="pop11" />
			<label for="pop11">投稿</label>
			<input type="radio" name="modalPop" id="pop12" />
			<label for="pop12">CLOSE</label>
			<input type="radio" name="modalPop" id="pop13" />
			<label for="pop13">×</label>
			<div class="modalPopup2">
				<div class="modalPopup3">
					<h2 class="modalTitle">投稿してね</h2>
					<div class="modalMain">
						<form:form modelAttribute="messageForm" method="post">
							<c:if test="${ not empty errorMessages }">
						    	<div class="errorMessages">
							        <c:forEach items="${errorMessages}" var="message">
							        	<c:out value="${message}" />
							        </c:forEach>
						        </div>
						        <c:remove var="errorMessages" scope="session"/>
						    </c:if><br>
							<form:textarea path="text" cols="60" rows="15" placeholder="本文を入力..."/>
								<p id="text-description">本文は400字以下で入力してください</p>
								<textarea id="hashtag-form" name="hashtag_name" cols="30" rows="8" placeholder="タグを入力..."></textarea>
								<input type="hidden" name="user_id" value="${loginUser.id}">
								<input type="hidden" name="loginUser" value="${loginUser.admin_flg}">
								<p id="hashtag-description">ハッシュタグは「全角スペース」「半角スペース」「,」「、」で区切られます</p>
								<input type="submit" name="publish" value="投稿" class="publish-btn"/>
						</form:form>
					</div>
				</div>
			 </div>
		</span>
	</span> --%>


<div class="right-area">


 		<%-- <p><c:if test="${textList.hashtag_name == null}">
 		<c:out value="${textList.hashtag_name}"></c:out></c:if></p> --%>
	<form:form modelAttribute="messageForm" method="post">
		<c:if test="${ not empty errorMessages }">
			<div class="errorMessages">
			    <c:forEach items="${errorMessages}" var="message">
			       	<c:out value="${message}" />
			    </c:forEach>
		    </div>

		    <c:remove var="errorMessages" scope="session"/>
		</c:if><br>

		<form:textarea path="text" cols="60" rows="8" maxlength="400" placeholder="本文は400字以内で書いてな"/>
		<!-- <p id="text-description">本文は400字以下で入力してください</p> -->

		<textarea id="hashtag-form" name="hashtag_name" cols="30" rows="2" maxlength="150"  placeholder="タグは「全角スペース」「半角スペース」「,」「、」で区切るで"></textarea>
		<input type="hidden" name="user_id" value="${loginUser.id}">
		<input type="hidden" name="loginUser" value="${loginUser.admin_flg}">
		<!-- <p id="hashtag-description">ハッシュタグは「全角スペース」「半角スペース」「,」「、」で区切られます</p> -->
		<input type="submit" name="publish" value="投稿するで" class="square_btn"/>

	</form:form>
	<div class="splitborder"></div>

	<div class="user-publishes">
		<c:forEach items="${textLists}" var="textList">
			 <c:if test="${textList.user_id == loginUser.id }">
				<form:form modelAttribute="messageForm" method="post">
					<input type="hidden" name="publish_id" value="${textList.id}">
					<div class="delete">
					<button type="submit" name="deleteMessage" class="publish-delete-btn" onClick="return disp();">
					<i class="fas fa-trash-alt fa-lg"></i>
					</button></div>
				</form:form>
			 </c:if>

			<p class="publish-text"><c:out value="${textList.text}"></c:out></p>
			<p class="publish-hashtag">
				<c:if test="${ not empty textList.hashtag_name }">
	 				#<c:out value="${textList.hashtag_name}"></c:out>
	 			</c:if>
	 		</p>
	 		<p class="publish-created-date">
	 			<c:out value="${textList.created_date}"></c:out>
	 		</p>


	 		<%-- <p><c:if test="${textList.hashtag_name == null}">
	 		<c:out value="${textList.hashtag_name}"></c:out></c:if></p> --%>
			<p class="publish-user">by<c:out value="${loginUser.name}"></c:out></p>
					<input type="hidden" name="loginUser_id" value="${loginUser.id}">

			<c:if test="${ empty textList.text }">
			<c:out value="${messages}" /></c:if>

		</c:forEach>

		<c:forEach items= "${messages}">
		</c:forEach>
	</div>
</div>



<script type="text/javascript">
<!--
function disp(){
	if(window.confirm('この投稿を削除しますか？')){
		return true;
	}else{
		window.alert('キャンセルされました');
		return false;
	}
}
// -->
</script>
</body>
</html>